version: '3'
services:
  scores-srv:
    build: .
    ports:
      - 8777:8777
    depends_on:
      - scores-db
  scores-db:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: adminroot
      MARIADB_USER: scores
      MARIADB_PASSWORD: scores
      MARIADB_DATABASE: scoresdb
  jenkins:
    image: jenkins/jenkins:latest
    ports:
      - 8080:8080 
      - 8000:80 
      - 50000:50000
      - 443:443
    volumes:
      - jenkins_data:/jenkins/jenkins-data
    environment:
      JENKINS_PASSWORD : bitnami
      JENKINS_USERNAME : admin
      JENKINS_EMAIL : idubi.pro@gmail.com
volumes:
  jenkins_data:
    driver: local
    driver_opts:
      device: D:\\projects\\WorldOfGame\\jenkins\\jenkins-data
networks:
  jenkins-network:
    name: jenkins-network
    external: true
  





