# Start from Ubuntu base image
FROM ubuntu:latest

# Install Docker
RUN apt-get update && \
    apt-get install -y apt-transport-https ca-certificates curl software-properties-common && \
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - && \
    add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" && \
    apt-get update && \
    apt-get install -y docker.io

# Install Nginx
RUN apt-get install -y nginx
# Copy Nginx configuration file (if you have a custom one)
# COPY nginx.conf /etc/nginx/nginx.conf

# Set up the command to run when starting the container
CMD service docker start && nginx -g 'daemon off;'